services:
  - type: web
    name: quantiq-python
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false

  - type: web
    name: quantiq-go
    runtime: go
    rootDir: backend
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PYTHON_SERVICE_URL
        value: https://finance-ai-bt9x.onrender.com
      - key: PORT
        value: "8000"
